#!/bin/bash
# MateCat web + build container entrypoint.
set -Eeuo pipefail
cd /var/www/html

# Shared PHP<->Node auth secret for the SSE server. PHP creates it on bootstrap,
# but the Node server needs it at startup, so provision it here (ASCII, both read it).
[ -f inc/login_secret.dat ] || head -c 96 /dev/urandom | base64 | tr -d '\n' > inc/login_secret.dat

echo "[app] waiting for MySQL (db:3306)…"
until (exec 3<>/dev/tcp/db/3306) 2>/dev/null; do sleep 2; done
echo "[app] MySQL is up."

# --- inc/config.ini (generated each start from environment; gitignored) ---
cat > inc/config.ini <<EOF
; GENERATED by docker-local — do not edit here, change docker-local/.env instead.
; (inc/config.ini* is gitignored)
ENV = "development"
CHECK_FS = no
BLACKLIST_FILE_SIZE_MAX = 2097152

[development]
PRINT_ERRORS = true
CLI_HTTP_HOST = "${MATECAT_BASE_URL}"
COOKIE_DOMAIN = "localhost"
ENABLE_MULTI_DOMAIN_API = no

DB_SERVER = "db"
DB_DATABASE = "matecat"
DB_USER = "matecat_user"
DB_PASS = "matecat_user"

REDIS_SERVERS = "tcp://redis:6379?database=0"
QUEUE_BROKER_ADDRESS = "tcp://amq:61613"
QUEUE_JMX_ADDRESS = "http://amq:8161"
QUEUE_CREDENTIALS = "admin:admin"
SOCKET_BASE_URL = "${SOCKET_BASE_URL}"
STORAGE_DIR = "/var/www/html/storage/files_storage"

SMTP_HOST = 'localhost'
SMTP_PORT = '25'
SMTP_SENDER = 'no-reply@matecat.loc'
SMTP_HOSTNAME = 'localhost'

FILTERS_ADDRESS = https://translated-matecat-filters-v1.p.rapidapi.com
FILTERS_RAPIDAPI_KEY = "${FILTERS_RAPIDAPI_KEY}"

; Local-disk file storage (no S3 needed)
FILE_STORAGE_METHOD = "fs"

; --- LexiQA --- browser calls LXQ_SERVER directly; feature gated on LXQ_LICENSE
LXQ_LICENSE = "${LXQ_LICENSE}"
LXQ_PARTNERID = "${LXQ_PARTNERID}"
LXQ_SERVER = "${LXQ_SERVER}"

AUTOLOAD_PLUGINS[] = "review_extended"
EOF
echo "[app] wrote inc/config.ini (ENV=development, LXQ_SERVER=${LXQ_SERVER})."

# Config files the bootstrap needs.
# The homepage always builds a "Sign in with Google" URL, which throws unless
# Google OAuth is fully configured — so write dummy-but-valid values (login will
# not actually work; anonymous project creation does). Replace with real
# credentials from Google Cloud Console if you need login.
if [ ! -f inc/oauth_config.ini ]; then
  cat > inc/oauth_config.ini <<EOF
[GOOGLE_OAUTH_CONFIG]
GOOGLE_OAUTH_CLIENT_ID       = "local-dev-client-id.apps.googleusercontent.com"
GOOGLE_OAUTH_CLIENT_SECRET   = "local-dev-client-secret"
GOOGLE_OAUTH_CLIENT_APP_NAME = "Matecat"
GOOGLE_OAUTH_BROWSER_API_KEY = "local-dev-browser-key"
GOOGLE_OAUTH_REDIRECT_URL    = "${MATECAT_BASE_URL}/oauth/response"
EOF
fi
[ -f inc/task_manager_config.ini ] || cp inc/task_manager_config.ini.sample inc/task_manager_config.ini

# PHP dependencies
if [ ! -f vendor/autoload.php ]; then
  echo "[app] composer install…"
  composer install --no-interaction --no-progress --prefer-dist
fi

# Frontend dependencies + build (produces public/build + lib/View/*.html)
if [ ! -x node_modules/.bin/vite ]; then
  echo "[app] yarn install…"
  # --ignore-engines: a lint-only devDependency demands node>=24; we build on 22.
  yarn install --frozen-lockfile --ignore-engines || yarn install --ignore-engines
fi
echo "[app] yarn build:dev…"
yarn build:dev

# Writable runtime dirs
mkdir -p storage/files_storage storage/log_archive
chmod -R 0777 storage || true

echo "[app] starting Apache on :80 (host http://localhost:8080)…"
exec apache2-foreground
