; MateCat local-dev PHP overrides
memory_limit = 1024M
upload_max_filesize = 128M
post_max_size = 128M
max_execution_time = 300
max_input_time = 300
short_open_tag = On
display_errors = On
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED
date.timezone = Europe/Rome
